import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import toast from 'react-hot-toast'
import { FiFileText, FiExternalLink, FiDownload, FiPlus, FiX } from 'react-icons/fi'
import { SiMicrosoftword, SiOverleaf } from 'react-icons/si'
import Navbar from '../components/Navbar'
import api from '../utils/api'
import useAuthStore from '../store/authStore'

// Base URL for downloading generated files from the backend.
// Falls back to localhost:5000 for local dev; override with VITE_API_BASE_URL in production.
const API_BASE_URL = import.meta.env?.VITE_API_BASE_URL || 'http://localhost:5000'

export default function ResumeBuilder() {
  const { user } = useAuthStore()
  const [step, setStep] = useState('form')
  const [generating, setGenerating] = useState(false)
  const [resumeData, setResumeData] = useState(null)
  const [format, setFormat] = useState(null)
  const [skills, setSkills] = useState([])
  const [skillInput, setSkillInput] = useState('')

  const [form, setForm] = useState({
    name: user?.name || '', email: user?.email || '', phone: '',
    targetRole: '', college: '', degree: '', gradYear: '', gpa: '',
    company: '', role: '', duration: '',
    projectTitle: '', projectTech: '', projectDesc: '',
    certificates: ''
  })

  const addSkill = () => {
    if (skillInput.trim() && !skills.includes(skillInput.trim())) {
      setSkills(prev => [...prev, skillInput.trim()])
      setSkillInput('')
    }
  }

  const handleGenerate = async () => {
    if (!form.name || !form.email) return toast.error('Name and email are required')
    setGenerating(true)
    try {
      const res = await api.post('/resume-builder/generate', {
        name: form.name, email: form.email, phone: form.phone,
        targetRole: form.targetRole,
        skills,
        education: [{ institution: form.college, degree: form.degree, year: form.gradYear, gpa: form.gpa }],
        experience: form.company ? [{ company: form.company, role: form.role, duration: form.duration }] : [],
        projects: form.projectTitle ? [{ title: form.projectTitle, tech: form.projectTech, description: form.projectDesc }] : [],
        certificates: form.certificates ? form.certificates.split(',').map(c => c.trim()) : []
      })

      if (!res.data?.success) {
        toast.error('Resume generation failed')
        return
      }

      // Keep the AI-generated resume data AND the backend's downloadUrl together,
      // instead of discarding downloadUrl like before.
      setResumeData({
        ...res.data.resumeData,
        downloadUrl: res.data.downloadUrl
      })
      setStep('select')
      toast.success('Resume generated by AI! 🎉')
    } catch (err) {
      toast.error('Generation failed')
    } finally {
      setGenerating(false)
    }
  }

  const handleWordDownload = () => {
    if (!resumeData?.downloadUrl) {
      toast.error('Resume not generated yet')
      return
    }

    // Just open the .docx that the backend already built with generator.js —
    // no more regenerating it client-side with docx/file-saver.
    window.open(`${API_BASE_URL}${resumeData.downloadUrl}`, '_blank')
    toast.success('Downloading Resume...')
  }

  const handleOverleaf = async () => {
    try {
      const res = await api.post('/resume-builder/latex', { resumeData })
      window.open('https://www.overleaf.com/latex/templates', '_blank')
      toast('Opening Overleaf — paste the LaTeX template to edit your resume', { duration: 5000 })
    } catch {
      window.open('https://www.overleaf.com', '_blank')
    }
  }

  return (
    <div className="animated-bg min-h-screen">
      <Navbar />
      <div className="pt-20 pb-12 px-4 max-w-3xl mx-auto">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <h1 className="text-3xl font-black mb-2">AI Resume <span className="gradient-text">Builder</span></h1>
          <p className="text-white/50 mb-8">Fill in your details — AI generates a professional, ATS-friendly resume</p>

          <AnimatePresence mode="wait">
            {step === 'form' && (
              <motion.div key="form" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="space-y-6">
                {/* Personal Info */}
                <div className="card">
                  <h3 className="font-bold mb-4">Personal Information</h3>
                  <div className="grid grid-cols-2 gap-4">
                    {[['name', 'Full Name', 'Yaswanth Kumar'], ['email', 'Email', 'you@email.com'],
                      ['phone', 'Phone', '+91 9876543210'], ['targetRole', 'Target Role', 'Full Stack Developer']
                    ].map(([key, label, placeholder]) => (
                      <div key={key}>
                        <label className="text-xs text-white/50 mb-1 block">{label}</label>
                        <input value={form[key]} onChange={e => setForm(p => ({ ...p, [key]: e.target.value }))}
                          placeholder={placeholder} className="input-field text-sm" />
                      </div>
                    ))}
                  </div>
                </div>

                {/* Skills */}
                <div className="card">
                  <h3 className="font-bold mb-4">Skills</h3>
                  <div className="flex gap-2 mb-3">
                    <input value={skillInput} onChange={e => setSkillInput(e.target.value)}
                      onKeyDown={e => e.key === 'Enter' && addSkill()}
                      placeholder="Add a skill (press Enter)" className="input-field text-sm flex-1" />
                    <button onClick={addSkill} className="btn-primary py-2 px-4 text-sm"><FiPlus /></button>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {skills.map(s => (
                      <span key={s} className="badge bg-primary-500/20 text-primary-300 border border-primary-500/30 flex items-center gap-1">
                        {s}
                        <button onClick={() => setSkills(p => p.filter(x => x !== s))} className="ml-1 text-white/40 hover:text-red-400"><FiX size={10} /></button>
                      </span>
                    ))}
                  </div>
                </div>

                {/* Education */}
                <div className="card">
                  <h3 className="font-bold mb-4">Education</h3>
                  <div className="grid grid-cols-2 gap-4">
                    {[['college', 'Institution', 'JNTU Hyderabad'], ['degree', 'Degree', 'B.Tech CSE'],
                      ['gradYear', 'Graduation Year', '2026'], ['gpa', 'GPA/CGPA', '8.5']
                    ].map(([key, label, placeholder]) => (
                      <div key={key}>
                        <label className="text-xs text-white/50 mb-1 block">{label}</label>
                        <input value={form[key]} onChange={e => setForm(p => ({ ...p, [key]: e.target.value }))}
                          placeholder={placeholder} className="input-field text-sm" />
                      </div>
                    ))}
                  </div>
                </div>

                {/* Experience */}
                <div className="card">
                  <h3 className="font-bold mb-4">Experience (optional)</h3>
                  <div className="grid grid-cols-2 gap-4">
                    {[['company', 'Company', 'Tech Corp'], ['role', 'Role', 'SDE Intern'],
                      ['duration', 'Duration', 'May 2025 – Jul 2025']
                    ].map(([key, label, placeholder]) => (
                      <div key={key} className={key === 'duration' ? 'col-span-2' : ''}>
                        <label className="text-xs text-white/50 mb-1 block">{label}</label>
                        <input value={form[key]} onChange={e => setForm(p => ({ ...p, [key]: e.target.value }))}
                          placeholder={placeholder} className="input-field text-sm" />
                      </div>
                    ))}
                  </div>
                </div>

                {/* Projects */}
                <div className="card">
                  <h3 className="font-bold mb-4">Project (optional)</h3>
                  <div className="space-y-3">
                    {[['projectTitle', 'Project Title', 'E-Commerce Platform'],
                      ['projectTech', 'Tech Stack', 'React, Node.js, MongoDB'],
                      ['projectDesc', 'Description', 'Built a full-stack...']
                    ].map(([key, label, placeholder]) => (
                      <div key={key}>
                        <label className="text-xs text-white/50 mb-1 block">{label}</label>
                        <input value={form[key]} onChange={e => setForm(p => ({ ...p, [key]: e.target.value }))}
                          placeholder={placeholder} className="input-field text-sm" />
                      </div>
                    ))}
                  </div>
                </div>

                {/* Certificates */}
                <div className="card">
                  <h3 className="font-bold mb-4">Certificates (comma separated)</h3>
                  <input value={form.certificates} onChange={e => setForm(p => ({ ...p, certificates: e.target.value }))}
                    placeholder="AWS Certified, MongoDB University, Google Cloud..." className="input-field text-sm" />
                </div>

                <button onClick={handleGenerate} disabled={generating} className="btn-primary w-full py-4 text-lg flex items-center justify-center gap-2">
                  {generating ? (
                    <><div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /> Generating Resume with AI...</>
                  ) : '🤖 Generate Resume with AI'}
                </button>
              </motion.div>
            )}

            {step === 'select' && (
              <motion.div key="select" initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="space-y-6">
                <div className="card text-center border-emerald-500/30">
                  <div className="text-4xl mb-3">🎉</div>
                  <h2 className="text-2xl font-black mb-2">Resume Generated!</h2>
                  <p className="text-white/50">Choose your preferred format to download</p>
                </div>

                {resumeData?.summary && (
                  <div className="card">
                    <h3 className="font-bold mb-2">AI Summary</h3>
                    <p className="text-white/70 text-sm leading-relaxed">{resumeData.summary}</p>
                  </div>
                )}

                <p className="text-white/50 text-center text-sm">Select how you want to export your resume:</p>

                <div className="grid grid-cols-2 gap-6">
                  <motion.button whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
                    onClick={handleWordDownload}
                    className="card border-blue-500/30 hover:border-blue-500/60 hover:bg-blue-500/10 transition-all flex flex-col items-center gap-4 py-8 cursor-pointer">
                    <div className="w-16 h-16 rounded-2xl bg-blue-500/20 flex items-center justify-center">
                      <SiMicrosoftword size={36} className="text-blue-400" />
                    </div>
                    <div className="text-center">
                      <div className="text-xl font-black">WORD DOC</div>
                      <div className="text-white/40 text-sm mt-1">Download .docx file</div>
                    </div>
                    <div className="flex items-center gap-1 text-blue-400 text-sm"><FiDownload size={14} /> Download</div>
                  </motion.button>

                  <motion.button whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
                    onClick={handleOverleaf}
                    className="card border-emerald-500/30 hover:border-emerald-500/60 hover:bg-emerald-500/10 transition-all flex flex-col items-center gap-4 py-8 cursor-pointer">
                    <div className="w-16 h-16 rounded-2xl bg-emerald-500/20 flex items-center justify-center">
                      <SiOverleaf size={36} className="text-emerald-400" />
                    </div>
                    <div className="text-center">
                      <div className="text-xl font-black">OVERLEAF</div>
                      <div className="text-white/40 text-sm mt-1">LaTeX template</div>
                    </div>
                    <div className="flex items-center gap-1 text-emerald-400 text-sm"><FiExternalLink size={14} /> Open Overleaf</div>
                  </motion.button>
                </div>

                <button onClick={() => setStep('form')} className="btn-outline w-full text-center py-3">← Edit Information</button>
              </motion.div>
            )}
          </AnimatePresence>
        </motion.div>
      </div>
    </div>
  )
}
